# Generated by Django 5.0 on 2024-01-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='post',
        ),
    ]
